// Policy form constants
export const PROPERTY_TYPES = [
  "Residential House",
  "Apartment/Condo",
  "Commercial Building",
  "Industrial Facility",
  "Mixed Use",
] as const;

export const CONSTRUCTION_MATERIALS = [
  "Concrete Block",
  "Steel Frame",
  "Wood Frame",
  "Brick",
  "Stone",
  "Mixed Materials",
] as const;

export const COVERAGE_TYPES = [
  "Contract Works Coverage",
    "Public Liability Coverage",
    "Employers Liability Coverage",
    "Contractors Plant and Equipment Coverage",
    "Professional Indemnity",
] as const;

export const POLICY_DURATIONS = [
  "3 Months (Short-term Project)",
  "6 Months",
  "1 Year",
  "Project-Based (Until Completion)",
] as const;

export const ADDITIONAL_COVERAGE_OPTIONS = [
  "Flood and Storm Damage",
  "Theft or Vandalism at Site",
  "Collapse or Structural Failure",
  "Third-Party Property Damage",
  "Injury to Non-Employees (Public)",
  "Machinery Breakdown",
  "Temporary Structures (Scaffolding, Site Office)",
  "Fire and Explosion",
  "Debris Removal Costs",
  "Cross Liability (Between Contractors/Subcontractors)",
] as const;

// Policy status constants
export const POLICY_STATUSES = {
  SUBMITTED: 'submitted',
  ASSIGNED: 'assigned',
  SURVEYED: 'surveyed',
  APPROVED: 'approved',
  REJECTED: 'rejected',
  REQUIRES_MORE_INFO: 'requires_more_info',
  COMPLETED: 'completed',
  SENT_TO_USER: 'sent_to_user'
} as const;

// Priority levels
export const PRIORITY_LEVELS = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  URGENT: 'urgent'
} as const;

export const CADASTRAL_ZONES = [
  "A00",
  "A01",
  "A02",
  "A03",
  "A04",
  "A05",
  "A06",
  "A07",
  "A08",
  "A09",
  "A10",
  "A11",
  "A12",
  "A13",
  "A14",
  "B00",
  "B01",
  "B02",
  "B03",
  "B04",
  "B05",
  "B06",
  "B07",
  "B08",
  "B09",
  "B10",
  "B11",
  "B12",
  "B13",
  "B14",
  "B15",
  "B16",
  "B17",
  "B18",
  "B19",
  "C00",
  "C01",
  "C02",
  "C03",
  "C04",
  "C05",
  "C06",
  "C07",
  "C08",
  "C09",
  "C10",
  "C11",
  "C12",
  "C13",
  "C14",
  "C15",
  "C16",
  "C17",
  "C18",
  "C19",
  "C20",
  "C21",
  "C22",
  "C23",
  "C24",
  "C25",
  "C26",
  "C27",
  "C28",
  "C29",
  "D00",
  "D01",
  "D02",
  "D03",
  "D04",
  "D05",
  "D06",
  "D07",
  "D08",
  "D09",
  "D10",
  "D11",
  "D12",
  "D13",
  "D14",
  "D15",
  "D16",
  "D17",
  "D18",
  "D19",
  "D20",
  "D21",
  "D22",
  "D23",
  "D24",
  "D25",
  "D26",
  "D27",
  "D28",
  "D29",
  "D30",
  "D31",
  "D32",
  "D33",
  "D34",
  "D35",
  "D36",
  "D37",
  "D38",
  "D39",
  "D40",
  "D41",
  "D42"
] as const;