import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/context/AuthProvider";

//always run npm run lint to heck errors before deployment 
import CookieConsent from "@/components/CookieConsent"
import ChatWidget from "@/components/ChatWidget"
import { Toaster} from "sonner"


export const metadata: Metadata = {
  title: "FCT-DCIP",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg"
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>{children}</AuthProvider>
        <CookieConsent />
        <ChatWidget />
        <Toaster
          richColors
          position="top-right"
          toastOptions={{
            duration: 4000, // 4s auto-close
            classNames: {
              toast: "rounded-lg shadow-md font-semibold",
              title: "text-base",
              description: "text-sm text-gray-200",
            },
          }}
        />
      </body>


    </html>
  );
}