/**
 * Token setup utility for development and testing
 * This file sets up authentication tokens for different user types
 * 
 * IMPORTANT: Development tokens are now DISABLED by default.
 * You must log in with real credentials to get valid JWT tokens.
 * 
 * If you need to use development tokens, they must be valid JWT tokens
 * generated by the backend, not fake placeholder strings.
 */

// Development tokens - MUST be valid JWT tokens from backend
// These are intentionally left empty to force proper login flow
const DEVELOPMENT_TOKENS = {
    niaAdmin: '',
    ammcAdmin: '',
    superAdmin: '',
    surveyor: '',
    user: ''
};

/**
 * Set up development tokens for testing
 * DISABLED: This function no longer sets fake tokens
 */
export const setupDevelopmentTokens = (): void => {
    if (typeof window === 'undefined') return;

    // Only set tokens if they are provided and valid (not empty)
    if (process.env.NODE_ENV === 'development') {
        Object.entries(DEVELOPMENT_TOKENS).forEach(([key, token]) => {
            if (token && token.length > 0) {
                const tokenKey = key === 'user' ? 'userToken' :
                    key === 'ammcAdmin' ? 'adminToken' :
                        key === 'superAdmin' ? 'superAdminToken' :
                            key === 'niaAdmin' ? 'niaAdminToken' :
                                key === 'surveyor' ? 'surveyorToken' : null;

                if (tokenKey && !localStorage.getItem(tokenKey)) {
                    localStorage.setItem(tokenKey, token);
                }
            }
        });
    }
};

/**
 * Clear all development tokens
 */
export const clearDevelopmentTokens = (): void => {
    if (typeof window === 'undefined') return;

    const tokenKeys = [
        'niaAdminToken',
        'adminToken',
        'superAdminToken',
        'surveyorToken',
        'userToken',
        'token',
        'authToken'
    ];

    tokenKeys.forEach(key => {
        localStorage.removeItem(key);
    });
};

/**
 * Get current token status
 */
export const getTokenStatus = (): Record<string, boolean> => {
    if (typeof window === 'undefined') return {};

    return {
        niaAdmin: !!localStorage.getItem('niaAdminToken'),
        ammcAdmin: !!localStorage.getItem('adminToken'),
        superAdmin: !!localStorage.getItem('superAdminToken'),
        surveyor: !!localStorage.getItem('surveyorToken'),
        user: !!localStorage.getItem('userToken'),
        legacy: !!(localStorage.getItem('token') || localStorage.getItem('authToken'))
    };
};

// Auto-setup tokens in development - DISABLED
// Users must log in to get valid JWT tokens
// if (typeof window !== 'undefined' && process.env.NODE_ENV === 'development') {
//     setupDevelopmentTokens();
// }